# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DialogOrientGainRef.ui'
#
# Created: Mon Oct 24 17:17:37 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DialogOrientGainRef(object):
    def setupUi(self, DialogOrientGainRef):
        DialogOrientGainRef.setObjectName("DialogOrientGainRef")
        DialogOrientGainRef.resize(424, 284)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../zorro_dev/automator/CINAlogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogOrientGainRef.setWindowIcon(icon)
        DialogOrientGainRef.setStyleSheet("background: rgb(0, 85, 127);\n"
"color: white;\n"
"font-weight: bold;\n"
"")
        self.frame = QtGui.QFrame(DialogOrientGainRef)
        self.frame.setGeometry(QtCore.QRect(0, 0, 421, 281))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.tbOrientGain_TargetStack = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbOrientGain_TargetStack.sizePolicy().hasHeightForWidth())
        self.tbOrientGain_TargetStack.setSizePolicy(sizePolicy)
        self.tbOrientGain_TargetStack.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbOrientGain_TargetStack.setStyleSheet("background: gray;\n"
"")
        self.tbOrientGain_TargetStack.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../zorro_dev/automator/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbOrientGain_TargetStack.setIcon(icon1)
        self.tbOrientGain_TargetStack.setIconSize(QtCore.QSize(32, 32))
        self.tbOrientGain_TargetStack.setObjectName("tbOrientGain_TargetStack")
        self.gridLayout.addWidget(self.tbOrientGain_TargetStack, 3, 3, 1, 1)
        self.leInputPath = QtGui.QLineEdit(self.frame)
        self.leInputPath.setMinimumSize(QtCore.QSize(0, 0))
        self.leInputPath.setStyleSheet("background: gray;\n"
"color: black;")
        self.leInputPath.setText("")
        self.leInputPath.setObjectName("leInputPath")
        self.gridLayout.addWidget(self.leInputPath, 3, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbApplyHotpixFilt = QtGui.QCheckBox(self.frame_2)
        self.cbApplyHotpixFilt.setChecked(True)
        self.cbApplyHotpixFilt.setObjectName("cbApplyHotpixFilt")
        self.horizontalLayout.addWidget(self.cbApplyHotpixFilt)
        self.gridLayout.addWidget(self.frame_2, 15, 0, 1, 1)
        self.line = QtGui.QFrame(self.frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 2, 1, 1)
        self.cbDoCorrel = QtGui.QCheckBox(self.frame)
        self.cbDoCorrel.setObjectName("cbDoCorrel")
        self.gridLayout.addWidget(self.cbDoCorrel, 16, 0, 1, 1)
        self.cbStackInHole = QtGui.QCheckBox(self.frame)
        self.cbStackInHole.setObjectName("cbStackInHole")
        self.gridLayout.addWidget(self.cbStackInHole, 8, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 13, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.horizontalFrame = QtGui.QFrame(self.frame)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtGui.QLabel(self.horizontalFrame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.sbHotpixRelax = QtGui.QDoubleSpinBox(self.horizontalFrame)
        self.sbHotpixRelax.setMinimumSize(QtCore.QSize(0, 36))
        self.sbHotpixRelax.setStyleSheet("background: white;\n"
"color:black;")
        self.sbHotpixRelax.setDecimals(3)
        self.sbHotpixRelax.setMaximum(2.0)
        self.sbHotpixRelax.setProperty("value", 0.95)
        self.sbHotpixRelax.setObjectName("sbHotpixRelax")
        self.horizontalLayout_2.addWidget(self.sbHotpixRelax)
        self.gridLayout.addWidget(self.horizontalFrame, 17, 0, 1, 1)
        self.tbOrientGain_GainRef = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbOrientGain_GainRef.sizePolicy().hasHeightForWidth())
        self.tbOrientGain_GainRef.setSizePolicy(sizePolicy)
        self.tbOrientGain_GainRef.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbOrientGain_GainRef.setStyleSheet("background: gray;\n"
"")
        self.tbOrientGain_GainRef.setText("")
        self.tbOrientGain_GainRef.setIcon(icon1)
        self.tbOrientGain_GainRef.setIconSize(QtCore.QSize(32, 32))
        self.tbOrientGain_GainRef.setObjectName("tbOrientGain_GainRef")
        self.gridLayout.addWidget(self.tbOrientGain_GainRef, 14, 3, 1, 1)
        self.leGainRefPath = QtGui.QLineEdit(self.frame)
        self.leGainRefPath.setEnabled(True)
        self.leGainRefPath.setStyleSheet("background: gray;\n"
"color: black;")
        self.leGainRefPath.setText("")
        self.leGainRefPath.setObjectName("leGainRefPath")
        self.gridLayout.addWidget(self.leGainRefPath, 14, 0, 1, 1)
        self.pbRun = QtGui.QPushButton(self.frame)
        self.pbRun.setStyleSheet("color:black;\n"
"background: gray;")
        self.pbRun.setObjectName("pbRun")
        self.gridLayout.addWidget(self.pbRun, 17, 3, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.frame)
        self.progressBar.setEnabled(True)
        self.progressBar.setStyleSheet("background: rgb(0, 85, 127);")
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 18, 0, 1, 1)

        self.retranslateUi(DialogOrientGainRef)
        QtCore.QMetaObject.connectSlotsByName(DialogOrientGainRef)
        DialogOrientGainRef.setTabOrder(self.leInputPath, self.leGainRefPath)

    def retranslateUi(self, DialogOrientGainRef):
        DialogOrientGainRef.setWindowTitle(QtGui.QApplication.translate("DialogOrientGainRef", "Orient Gain Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.leInputPath.setToolTip(QtGui.QApplication.translate("DialogOrientGainRef", "The directory to watch for new *.mrc, *.dm4, *.tif, and *.hdf5 files for processing.  Moves _all_ files in this directory.", None, QtGui.QApplication.UnicodeUTF8))
        self.cbApplyHotpixFilt.setText(QtGui.QApplication.translate("DialogOrientGainRef", "Apply Outlier Pixel Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.cbDoCorrel.setText(QtGui.QApplication.translate("DialogOrientGainRef", "Calculate Correlated Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.cbStackInHole.setText(QtGui.QApplication.translate("DialogOrientGainRef", "Stack is in a Hole", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogOrientGainRef", "Gain reference:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setToolTip(QtGui.QApplication.translate("DialogOrientGainRef", "The directory to watch for new *.mrc, *.dm4, *.tif, and *.hdf5 files for processing.  Moves _all_ files in this directory.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogOrientGainRef", "Target stack:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogOrientGainRef", "Outlier relaxation:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRun.setText(QtGui.QApplication.translate("DialogOrientGainRef", "Run", None, QtGui.QApplication.UnicodeUTF8))

