# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ViewWidget.ui'
#
# Created: Mon Oct 24 17:17:36 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ViewWidget(object):
    def setupUi(self, ViewWidget):
        ViewWidget.setObjectName("ViewWidget")
        ViewWidget.setEnabled(True)
        ViewWidget.resize(571, 505)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ViewWidget.sizePolicy().hasHeightForWidth())
        ViewWidget.setSizePolicy(sizePolicy)
        ViewWidget.setStyleSheet("")
        self.verticalLayout = QtGui.QVBoxLayout(ViewWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameTopV = QtGui.QFrame(ViewWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTopV.sizePolicy().hasHeightForWidth())
        self.frameTopV.setSizePolicy(sizePolicy)
        self.frameTopV.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameTopV.setStyleSheet("")
        self.frameTopV.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTopV.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTopV.setObjectName("frameTopV")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frameTopV)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tbPopoutView = QtGui.QToolButton(self.frameTopV)
        self.tbPopoutView.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/application-resize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPopoutView.setIcon(icon)
        self.tbPopoutView.setCheckable(False)
        self.tbPopoutView.setObjectName("tbPopoutView")
        self.horizontalLayout_5.addWidget(self.tbPopoutView)
        self.tbLive = QtGui.QToolButton(self.frameTopV)
        self.tbLive.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tbLive.setStyleSheet("")
        self.tbLive.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/monitor-live.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("icons/monitor-dead.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLive.setIcon(icon1)
        self.tbLive.setCheckable(True)
        self.tbLive.setChecked(True)
        self.tbLive.setObjectName("tbLive")
        self.horizontalLayout_5.addWidget(self.tbLive)
        self.tbChangeColormap = QtGui.QToolButton(self.frameTopV)
        self.tbChangeColormap.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbChangeColormap.setIcon(icon2)
        self.tbChangeColormap.setObjectName("tbChangeColormap")
        self.horizontalLayout_5.addWidget(self.tbChangeColormap)
        self.tbToggleColorbar = QtGui.QToolButton(self.frameTopV)
        self.tbToggleColorbar.setMinimumSize(QtCore.QSize(23, 22))
        self.tbToggleColorbar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/colorbar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbToggleColorbar.setIcon(icon3)
        self.tbToggleColorbar.setCheckable(True)
        self.tbToggleColorbar.setChecked(True)
        self.tbToggleColorbar.setObjectName("tbToggleColorbar")
        self.horizontalLayout_5.addWidget(self.tbToggleColorbar)
        self.tbZoomIn = QtGui.QToolButton(self.frameTopV)
        self.tbZoomIn.setEnabled(False)
        self.tbZoomIn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/magnifier-zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbZoomIn.setIcon(icon4)
        self.tbZoomIn.setObjectName("tbZoomIn")
        self.horizontalLayout_5.addWidget(self.tbZoomIn)
        self.tbZoomOut = QtGui.QToolButton(self.frameTopV)
        self.tbZoomOut.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/magnifier-zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbZoomOut.setIcon(icon5)
        self.tbZoomOut.setObjectName("tbZoomOut")
        self.horizontalLayout_5.addWidget(self.tbZoomOut)
        self.tbShowBoxes = QtGui.QToolButton(self.frameTopV)
        self.tbShowBoxes.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/boxes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbShowBoxes.setIcon(icon6)
        self.tbShowBoxes.setCheckable(True)
        self.tbShowBoxes.setChecked(False)
        self.tbShowBoxes.setObjectName("tbShowBoxes")
        self.horizontalLayout_5.addWidget(self.tbShowBoxes)
        self.tbLogIntensity = QtGui.QToolButton(self.frameTopV)
        self.tbLogIntensity.setEnabled(False)
        self.tbLogIntensity.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/logscale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLogIntensity.setIcon(icon7)
        self.tbLogIntensity.setCheckable(True)
        self.tbLogIntensity.setObjectName("tbLogIntensity")
        self.horizontalLayout_5.addWidget(self.tbLogIntensity)
        self.tbToggleHistogramContrast = QtGui.QToolButton(self.frameTopV)
        self.tbToggleHistogramContrast.setEnabled(False)
        self.tbToggleHistogramContrast.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/histogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbToggleHistogramContrast.setIcon(icon8)
        self.tbToggleHistogramContrast.setCheckable(True)
        self.tbToggleHistogramContrast.setChecked(True)
        self.tbToggleHistogramContrast.setObjectName("tbToggleHistogramContrast")
        self.horizontalLayout_5.addWidget(self.tbToggleHistogramContrast)
        self.sbHistogramCutoff = QtGui.QSpinBox(self.frameTopV)
        self.sbHistogramCutoff.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbHistogramCutoff.sizePolicy().hasHeightForWidth())
        self.sbHistogramCutoff.setSizePolicy(sizePolicy)
        self.sbHistogramCutoff.setStyleSheet("border-radius: 0px;")
        self.sbHistogramCutoff.setMinimum(-5)
        self.sbHistogramCutoff.setMaximum(5)
        self.sbHistogramCutoff.setProperty("value", -3)
        self.sbHistogramCutoff.setObjectName("sbHistogramCutoff")
        self.horizontalLayout_5.addWidget(self.sbHistogramCutoff)
        self.tbPrevImage = QtGui.QToolButton(self.frameTopV)
        self.tbPrevImage.setEnabled(False)
        self.tbPrevImage.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/arrow-180.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPrevImage.setIcon(icon9)
        self.tbPrevImage.setObjectName("tbPrevImage")
        self.horizontalLayout_5.addWidget(self.tbPrevImage)
        self.leImageIndex = QtGui.QLineEdit(self.frameTopV)
        self.leImageIndex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leImageIndex.sizePolicy().hasHeightForWidth())
        self.leImageIndex.setSizePolicy(sizePolicy)
        self.leImageIndex.setMinimumSize(QtCore.QSize(0, 0))
        self.leImageIndex.setMaximumSize(QtCore.QSize(25, 16777215))
        self.leImageIndex.setStyleSheet("border-radius: 0px;")
        self.leImageIndex.setObjectName("leImageIndex")
        self.horizontalLayout_5.addWidget(self.leImageIndex)
        self.tbNextImage = QtGui.QToolButton(self.frameTopV)
        self.tbNextImage.setEnabled(False)
        self.tbNextImage.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbNextImage.setIcon(icon10)
        self.tbNextImage.setObjectName("tbNextImage")
        self.horizontalLayout_5.addWidget(self.tbNextImage)
        self.comboView = QtGui.QComboBox(self.frameTopV)
        self.comboView.setMinimumSize(QtCore.QSize(150, 0))
        self.comboView.setObjectName("comboView")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.comboView.addItem("")
        self.horizontalLayout_5.addWidget(self.comboView)
        self.verticalLayout.addWidget(self.frameTopV)
        self.viewCanvas = MplCanvas(ViewWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewCanvas.sizePolicy().hasHeightForWidth())
        self.viewCanvas.setSizePolicy(sizePolicy)
        self.viewCanvas.setMinimumSize(QtCore.QSize(0, 0))
        self.viewCanvas.setCursor(QtCore.Qt.CrossCursor)
        self.viewCanvas.setStyleSheet("")
        self.viewCanvas.setObjectName("viewCanvas")
        self.verticalLayout.addWidget(self.viewCanvas)

        self.retranslateUi(ViewWidget)
        QtCore.QMetaObject.connectSlotsByName(ViewWidget)

    def retranslateUi(self, ViewWidget):
        ViewWidget.setWindowTitle(QtGui.QApplication.translate("ViewWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.frameTopV.setProperty("class", QtGui.QApplication.translate("ViewWidget", "TopFrame", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPopoutView.setToolTip(QtGui.QApplication.translate("ViewWidget", "Pop-out window( shortcut: \'enter\')", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPopoutView.setShortcut(QtGui.QApplication.translate("ViewWidget", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLive.setToolTip(QtGui.QApplication.translate("ViewWidget", "Live rendering (shortcut \'d\')", None, QtGui.QApplication.UnicodeUTF8))
        self.tbChangeColormap.setToolTip(QtGui.QApplication.translate("ViewWidget", "Change colormap (shortcut: \'c\')", None, QtGui.QApplication.UnicodeUTF8))
        self.tbChangeColormap.setShortcut(QtGui.QApplication.translate("ViewWidget", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.tbToggleColorbar.setToolTip(QtGui.QApplication.translate("ViewWidget", "Toggle colorbar (shortcut: \'b\')", None, QtGui.QApplication.UnicodeUTF8))
        self.tbZoomIn.setToolTip(QtGui.QApplication.translate("ViewWidget", "Zoom in (shortcut: \'i\')", None, QtGui.QApplication.UnicodeUTF8))
        self.tbZoomIn.setShortcut(QtGui.QApplication.translate("ViewWidget", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.tbZoomOut.setToolTip(QtGui.QApplication.translate("ViewWidget", "Zoom out (shortcut: \'o\')", None, QtGui.QApplication.UnicodeUTF8))
        self.tbZoomOut.setText(QtGui.QApplication.translate("ViewWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbZoomOut.setShortcut(QtGui.QApplication.translate("ViewWidget", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.tbShowBoxes.setToolTip(QtGui.QApplication.translate("ViewWidget", "Particle boxes (shortcut \'space\')", None, QtGui.QApplication.UnicodeUTF8))
        self.tbShowBoxes.setShortcut(QtGui.QApplication.translate("ViewWidget", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLogIntensity.setToolTip(QtGui.QApplication.translate("ViewWidget", "Log intensity (shortcut: \'l\')", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLogIntensity.setShortcut(QtGui.QApplication.translate("ViewWidget", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.tbToggleHistogramContrast.setToolTip(QtGui.QApplication.translate("ViewWidget", "Toggle histogram contrast limits (shortcut: \'h\')", None, QtGui.QApplication.UnicodeUTF8))
        self.tbToggleHistogramContrast.setShortcut(QtGui.QApplication.translate("ViewWidget", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPrevImage.setToolTip(QtGui.QApplication.translate("ViewWidget", "Previous image (shortcut: \'p\' or \'P\')", None, QtGui.QApplication.UnicodeUTF8))
        self.leImageIndex.setText(QtGui.QApplication.translate("ViewWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tbNextImage.setToolTip(QtGui.QApplication.translate("ViewWidget", "Next image (shortcut: \'n\' or \'N\')", None, QtGui.QApplication.UnicodeUTF8))
        self.tbNextImage.setShortcut(QtGui.QApplication.translate("ViewWidget", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(0, QtGui.QApplication.translate("ViewWidget", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(1, QtGui.QApplication.translate("ViewWidget", "Drift", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(2, QtGui.QApplication.translate("ViewWidget", "Drift error", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(3, QtGui.QApplication.translate("ViewWidget", "Peak significance", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(4, QtGui.QApplication.translate("ViewWidget", "Correlation coefficient", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(5, QtGui.QApplication.translate("ViewWidget", "CTF diagnostic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(6, QtGui.QApplication.translate("ViewWidget", "Logistic weights", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(7, QtGui.QApplication.translate("ViewWidget", "Fourier Ring Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(8, QtGui.QApplication.translate("ViewWidget", "-----------------------------", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(9, QtGui.QApplication.translate("ViewWidget", "First image", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(10, QtGui.QApplication.translate("ViewWidget", "Image sum", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(11, QtGui.QApplication.translate("ViewWidget", "Dose filtered sum", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(12, QtGui.QApplication.translate("ViewWidget", "Fourier mag", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(13, QtGui.QApplication.translate("ViewWidget", "Polar mag", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(14, QtGui.QApplication.translate("ViewWidget", "Cross correlations", None, QtGui.QApplication.UnicodeUTF8))
        self.comboView.setItemText(15, QtGui.QApplication.translate("ViewWidget", "--------Gauto------------", None, QtGui.QApplication.UnicodeUTF8))

from .MplCanvas import MplCanvas
